import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY || '';

// Initialize Gemini Client
const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Removes the watermark using Gemini Nano Banana (gemini-2.5-flash-image)
 * We send the original image and the mask image, instructing the model to remove the masked area.
 */
export const removeWatermark = async (
  originalImageBase64: string,
  maskImageBase64: string
): Promise<string> => {
  try {
    // Detect MIME type from the base64 string
    const mimeMatch = originalImageBase64.match(/^data:(image\/[a-zA-Z+]+);base64,/);
    const mimeType = mimeMatch ? mimeMatch[1] : 'image/png';

    // Clean base64 strings (remove header)
    const cleanOriginal = originalImageBase64.replace(/^data:image\/[a-zA-Z+]+;base64,/, '');
    const cleanMask = maskImageBase64.replace(/^data:image\/[a-zA-Z+]+;base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: "Output the edited image only. I have provided two images. The first image is the original photo. The second image is a black and white mask where the white areas represent a watermark or object to be removed. Task: Remove the content in the first image that corresponds to the white areas in the mask image. Fill in the removed area with a coherent background that matches the surrounding texture and lighting of the first image. Do not change the aspect ratio or resolution.",
          },
          {
            inlineData: {
              mimeType: mimeType,
              data: cleanOriginal,
            },
          },
          {
            inlineData: {
              mimeType: 'image/png', // Mask is always PNG from canvas
              data: cleanMask,
            },
          },
        ],
      },
    });

    // Extract the image from the response
    let resultImageBase64 = '';
    
    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
       for (const part of response.candidates[0].content.parts) {
         if (part.inlineData && part.inlineData.data) {
           resultImageBase64 = `data:image/png;base64,${part.inlineData.data}`;
           break;
         }
       }
    }

    if (!resultImageBase64) {
      // Fallback: Check if there is text explaining why it failed (safety etc)
      const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
      if (text) {
          console.warn("Model returned text instead of image:", text);
          throw new Error("AI未能生成图片，可能触发了安全策略或无法处理该请求。");
      }
      throw new Error("No image generated by Gemini.");
    }

    return resultImageBase64;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};